### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by juanjoseluisgarcia** [gogearbox/gearbox#123]
Hi, 

This project has not had any activity for more than two years and links redirects to other pages.

**Comment by anyfig** [comment]
there are 3 Frameworks as i knew based on fasthttp (atreugo/fiber/gearbox) ,  
They are homogenous and almost the same in many aspects . you can choose the other two

**Comment by juanjoseluisgarcia** [comment]
That's a shame. I liked it very much.
