### ISSUE TITLE
[Proposal] Contribute to a benchmark

### ISSUE THREAD

**Issue by waghanza** [gogearbox/gearbox#27]
Hi,

I'm leading a benchmarking project => https://github.com/the-benchmarker/web-frameworks

The purpose of this project is to compare performances (other indicators will come), based on a fairest, as we can, comparison for `go` **frameworks** (comparing on the same version, **production-grade** environments, same compilation options ...).

Do you mind that I (or any member) add `gearbox`  ? :heart:

Regards,

**Comment by abahmed** [comment]
Hi @waghanza Thank you for reaching us. Surely, we don't mind and if you need any help while adding, just ping us

**Comment by waghanza** [comment]
I just see that I can not, yet, introduce `gearbox` in the above benchmark.

It needs #15 to support route `/user/:id` (I mean having a URL param)

**Comment by muhammednagy** [comment]
Please check our PR https://github.com/the-benchmarker/web-frameworks/pull/2961
