### ISSUE TITLE
my ubuntu i686 system get the wrong result

### ISSUE THREAD

**Issue by tomasky** [gogearbox/gearbox#75]
**Describe the bug**
```go
package main

import (
	"log"

	"github.com/gogearbox/gearbox"
)

func main() {
	gb := gearbox.New()
	logMiddleware := func(ctx gearbox.Context) {
		log.Printf("log message!")
		ctx.Next()
	}
	gb.Use(logMiddleware)
	routes := []*gearbox.Route{
		gb.Get("/id", func(ctx gearbox.Context) {
			ctx.SendString("User X")
		}),
		gb.Delete("/del", func(ctx gearbox.Context) {
			ctx.SendString("Deleted")
		}),
	}

	accountRoutes := gb.Group("/account", routes)
	gb.Group("/api", accountRoutes)
	gb.Start(":3000")
}
```
go run main.go
curl http://localhost:3000/api/account/id
output:  Deleted
**To Reproduce**

**Expected behavior**

**Actual behavior**
curl http://localhost:3000/api/account/id

 My x86 system result "Deleted"
 but my amd64 system result "User X" , it's so strange

**Version/Commit**
gear1.1.1    , go1.15.7

**Comment by abahmed** [comment]
Hey 👋 Thanks for reporting that. We are investigating this issue right now

**Comment by abahmed** [comment]
@tomasky  Which version of go do you use (go1.15.7.linux-386 **or** go1.15.7.linux-amd64)?
You can get that using **go version**

**Comment by tomasky** [comment]
go1.15.7.linux-386

**Comment by tomasky** [comment]
When i remove `gb.Use(logMiddleware)` ,it works well and has the right result

**Comment by abahmed** [comment]
@tomasky Managed to reproduce that on go1.15.7.linux-386 and trying to investigate that, BTW, it works on go1.15.7.linux-amd64

**Comment by tomasky** [comment]
Ok, thanks

**Comment by abahmed** [comment]
> When i remove `gb.Use(logMiddleware)` ,it works well and has the right result, but the
> 
> ```shell
> curl http://localhost:3000/api/account/del
> ```
> 
> output: `Deleted `
> it should return `Method Not Allowed`

@tomasky 
to enable Method Not Allowed, you need to configure it from settings as it's **not enabled** by default


`
gb := gearbox.New(&gearbox.Settings{
	HandleMethodNotAllowed: true,
})
`

**Comment by abahmed** [comment]
@tomasky  Gearbox v1.1.2 is released. It includes the fix for your issue. Please update your x86 system to it and confirm if your issue is resolved

**Comment by tomasky** [comment]
All right , now  all work well and the result is correct　,thanks

**Comment by abahmed** [comment]
You are welcome :-)
