### ISSUE TITLE
Pass data from middleware to handler 

### ISSUE THREAD

**Issue by stasandk** [gogearbox/gearbox#78]
**Is your feature request related to a problem? Please describe.**
I have a middleware that checks and parse the JWT. I would like to pass from that middleware to the handler the parsed JWT so I don't need to parse it again. I saw that the fiber has this feature but I didn't saw anything related here.

**Describe the solution you'd like**
Be able to set in context some data that will be available in the next middleware or handler

**Comment by abahmed** [comment]
Hey @stasandk 👋
Thanks for raising this. Your request is prioritized and this will be supported ASAP.

**Comment by stasandk** [comment]
Awesome! Love the simplicity of this framework, good job @abahmed 👏🏼

**Comment by abahmed** [comment]
@tomasky Gearbox v1.2.0 is released. It includes support for passing data from middleware to handler
