### ISSUE TITLE
Participate in the Tech Empower benchmark

### ISSUE THREAD

**Issue by amoorahmat** [gogearbox/gearbox#79]
please participate in the Tech Empower benchmark

**Comment by abahmed** [comment]
Hey @amoorahmat 👋 
We already participating in Tech Empower benchmark and you can check the latest results here (https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=composite)

**Comment by amoorahmat** [comment]
> Hey @amoorahmat 👋
> We already participating in Tech Empower benchmark and you can check the latest results here (https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=composite)

Yesss, Great result, Congratulation.
